version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "guatepass-dev"
s3_prefix = "guatepass-dev"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []
resolve_s3 = true

[default.build]
[default.build.parameters]
cached = true
parallel = true

